[IV-22-23] Objetivo 0
fjgallardo00/Akinah pull request #1
Opened 2022-09-22 10:39 UTC by fjgallardo00

* [ ] ¿Se trata de un problema real del que se tenga conocimiento personal?

Sí, pues el precio del aceite oscila y en cada cosecha anual varía el valor de ganancia

* [ ] ¿Se trata de un problema que para solucionar requiera el despliegue
   de una aplicación en la nube?
   
Sí, pues requiere de una predicción del precio del aceite a través del scrapping para la obtención de datos, el cálculo de del precio y la elaboración de una API

* [ ] ¿La solución requiere una cierta cantidad de lógica de negocio, en vez
    solucionarse sólo almacenando y buscando?
    
Sí, debe de obtener los datos de otras páginas para calcular y predecir el valor del aceite
    
* [ ] ¿Se ha incluído la configuración del repositorio y se ha enlazado desde el `README`?

Sí

2022-09-24 08:42 UTC, JJ requested changes
Veo varios problemas aquí.
1. El precio del aceite no afecta tanto a los productores como a los comercializadores.
2. No dejas claro cómo vas a predecirlo. Ni qué datos tienes ni qué lógica de negocio vas a usar
3. Tampoco está claro que predecir el precio vaya a solucionar algún tipo de problema.

Mientras que el problema puede ser interesante, sería conveniente que perfilaras todos esos aspectos para superar el objetivo.

2022-09-29 05:34 UTC, JJ commented
Aparte de los problemas comentados, ya hay otro proyecto que hace esto mismo. Salvo que tengas conocimiento de primera mano, yo cambiaría el campo.

2022-09-30 07:41 UTC, fjgallardo00 commented
@JJ 
El PR está listo para revisión de nuevo.

2022-09-30 11:34 UTC, JJ requested changes
No dices nada de la lógica de negocio.

2022-09-30 17:02 UTC, fjgallardo00 commented
Entonces creo que no he entendido el concepto de lógica de negocio porque pensaba que lo había incluido
@JJ

2022-09-30 17:49 UTC, JJ commented
> Entonces creo que no he entendido el concepto de lógica de negocio porque pensaba que lo había incluido @JJ

Es posible. El hecho es que no has dicho explícitamente qué algoritmos usarías como lógica de negocio para hacer las recomendaciones. Sólo has dicho lo que no vas a usar.

2022-10-05 12:04 UTC, fjgallardo00 commented
@JJ 
Ya he añadido la lógica de negocio. Está listo para revisión de nuevo.

2022-10-05 12:06 UTC, JJ commented on README.md
> +Para ello se usarán datos de libros extraídos de la página de Goodreads a través de un Scrapper ya realizado en otro [proyecto](https://github.com/scostap/goodreads_bbe_dataset). El objetivo es despl
Scraper lleva una sola p

2022-10-05 12:07 UTC, JJ commented on README.md
> +Para ello se usarán datos de libros extraídos de la página de Goodreads a través de un Scrapper ya realizado en otro [proyecto](https://github.com/scostap/goodreads_bbe_dataset). El objetivo es despl
No has terminado la frase.

2022-10-05 16:29 UTC, JJ approved these changes
:+1: si tienes claro que el algoritmo de Pearson tienes que implementarlo tú en el objetivo 4 (o quien toque)

2022-10-05 16:38 UTC, fjgallardo00 commented
@JJ 
Claro del todo no lo tengo pero es un algoritmo que funciona bastante parecido a como quiero que sea el proyecto. ¿Se podría cambiar más adelante?

2022-10-05 16:55 UTC, JJ commented
siempre que lo programes tú y sea "sustancial" si

El mié, 5 oct 2022, 18:39, Francisco Javier Gallardo Molina <
***@***.***> escribió:

> @JJ <https://github.com/JJ>
> Claro del todo no lo tengo pero es un algoritmo que funciona bastante
> parecido a como quiero que sea el proyecto. ¿Se podría cambiar más adelante?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/fjgallardo00/Akinah/pull/1#issuecomment-1268672950>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAAAD5FMGIPSKDK7SUYOFELWBWVKRANCNFSM6AAAAAAQS5HGCA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-10-06 11:17 UTC, merged