[IV-22-23] Objetivo 1
fjgallardo00/Akinah pull request #6
Opened 2022-10-14 07:49 UTC by fjgallardo00

# Milestones o PMV

* [X] ¿Las historias de usuario y los milestones constituyen una guía suficiente para poder comenzar el desarrollo de un proyecto?
* [X] ¿Los milestones están ordenados correctamente, de forma que el 1 o 0 sea lo primero que hay que empezar a publicar?
* [X] ¿Todos los milestones se construyen sobre el anterior, teniendo un orden lógico el desarrollo?
* [X] ¿El milestone 0 tiene asignada alguna historia de usuario?
* [X] ¿El milestone 0 corresponde con lo mencionado varias veces en clase, y en concreto con lo que se solicita en el objetivo siguiente?
* [X] ¿Todos los milestones describen correctamente un producto, y no un concepto vago, una funcionalidad o una tarea?
* [X] ¿Los milestones son graduales, o hay un salto grande entre ellos?
* [X] ¿Los milestones iniciales son internos, y hay a continuación milestones o productos externos?
* [X] ¿Los milestones son mínimos, es decir, incluyen un producto mínimamente viable para poder avanzar?
* [X] ¿El milestone 0 es mínimo *y* viable?
* [X] ¿Se indica claramente cómo comprobar la viabilidad del PMV de cada hito? Es decir, ¿se dice qué requisitos técnicos tiene que cumplir el producto de cada hito?
* [X] ¿Entre dos milestones consecutivos, no hay ningún PMV posible o por el contrario podrían desarrollarse muchas posibles etapas internas o externas de un proyecto?
    
# Historias de usuario  
    
* [X] ¿He tenido en cuenta en las historias de usuario que se trata de un proyecto que se desplegará en la nube?
* [X] ¿Están descritos todos los conceptos mencionados en las HUs con suficiente claridad, generalmente en documentos aparte?
* [X] ¿Tienen coherencia suficiente las historias de usuario, y en caso de que no lo tengan, se ha escrito un *user journey* para aclararlo?
* [X] ¿Todas las historias de usuario representan un beneficio para el mismo y se relacionan con la lógica de negocio? Es decir, ¿los usuarios *desean* hacerlo o tú deseas que el usuario te lo pida para hacerlo?

2022-10-17 11:20 UTC, JJ requested changes
Por favor, repasa bien los conceptos correspondientes a este objetivo.

2022-10-17 11:20 UTC, JJ commented on docs/Objetivo-1/historias_usuarios.md
> +- [HU0] Kaladin quiere una nueva novela que sea distópica y que sea de ficción.
Son demasiado concretos, no expresan claramente cuál es el beneficio para el usuario ni que necesite lógica de negocio. Deberías incluir también el contexto.

2022-10-17 11:20 UTC, JJ commented on docs/Objetivo-1/historias_usuarios.md
> +- [HU1] Shallan quiere cambiar de género de misterio y esta vez prefiere buscar un libro que sea una novela histórica.
Tampoco entiendo muy bien esto. ¿No se trataría simplemente de buscar? ¿Qué tiene que ver esto con la lógica de negocio?

2022-10-17 11:20 UTC, JJ commented on docs/Objetivo-1/milestones.md
> +- [M0] Estructura de datos para representar los libros. Dentro de la estructura debe de tener como mínimo los géneros o etiquetas asociadas a ese libro, el número de interacciones que tiene ese libro
Una estructura de datos no es un producto, como se ha dicho frecuentemente tanto en clase como en los errores frecuents. Por favor, revisa el concepto de producto.

2022-10-17 11:20 UTC, JJ commented on docs/Objetivo-1/milestones.md
> +- [M1] Método para añadir los datos de nuestro archivo de datos a la estructura de datos que representa los libros.
Un método no es un producto.

2022-10-20 11:59 UTC, fjgallardo00 commented
@JJ 
Listo para revisión. He reagrupado y cambiado las HU y he cambiado los Milestones

2022-10-21 07:59 UTC, fjgallardo00 commented
@JJ 
Listo para revisión.

2022-10-23 17:26 UTC, pedromarting3 commented
Buenas! @fjgallardo00 voy a intentar echarte una mano con el objetivo 1 para que lo superes lo antes posible!  

Hablando sobre las historias de usuario, hay algunas que le quieren dar el mismo uso al servicio (es el caso del #2 y #3 ) por lo que me centraría en una de ellas y así quitas complejidad. Ten en cuenta que las historias de usuario es algo muy útil a la hora de la implementación del objetivo 2 por parte de tu compañero así que yo las haría un poco mas completas. Intenta añadir un poco de explicación sobre la historia para que sea una historia de usuario real. En el caso del #4 podrías especificar el criterio a seguir a la hora de determinar "el mejor" libro (puntuación, visitas...)   

Hablando sobre los milestones, intenta formular los títulos de una forma diferente. Por ejemplo, en el m0 no queremos una estructura de datos, queremos un entregable. Es imprescindible especificar lo que vas a entregar en cada milestone. El resto de milestones hablan sobre métodos, un método no es un producto por lo que debes de buscar la forma de empaquetar estos elementos para convertirlos en productos. Por último, intenta añadir una descripción a cada milestone en el que se especifique cuando consideraremos el milestone superado.  

Intenta revisar esto y cuando me avises le vuelvo a echar un vistazo. A seguir!! 🚀

2022-10-24 12:28 UTC, fjgallardo00 commented
@pedromarting3 @JJ 
Listo para revisión. Creo que le echaste un vistazo a la primera versión de los Milestones y las HU @pedromarting3 , pero de todas formas gracias por echarle un vistazo a mi PR.

2022-10-25 10:25 UTC, JJ requested changes
Por favor, revisa una vez más los conceptos de "producto mínimamente viable", milestone e historia de usuario.

2022-10-25 10:25 UTC, JJ commented on docs/Objetivo-1/historias_usuarios.md
> +- [HU1] Quiero que se me recomiende un libro que me guste, indicando otro segundo libro para que me encuentre un libro lo más similar posible.
1. No refleja el problema original. Se trata de recomendar libros. Si sólo recomienda a quién ya sugiera un libro, no resuelve el problema original. En las historias de usuario hay que tratar de reflejar todas las posibles opciones del problema y ya las hablamos en clase.
2. Indicando "otro" excluye que se use la lista de lectura y tampoco refleja una lógica de negocio que sea demasiado compleja. Es buscar simplemente a otro libro que tenga distancia mínima. No tiene en cuenta si ya lo ha leído o no. En general, no refleja el problema original.

2022-10-25 10:25 UTC, JJ commented on docs/Objetivo-1/milestones.md
> +- [M0] Diseño de un módulo que defina la estructura de datos donde vayamos a almacenar libros y géneros.
Ya expliqué en clase, y a ti personalmente, que no se trata de ¨diseñar" "módulos" ni un diseño es un producto ni se trata de "estructuras de datos". Está en los errores frecuentes de esta semana y la pasada, y en general en todas las presentaciones que se han hecho. También te lo ha dicho @pedromarting3 
> Por ejemplo, en el m0 no queremos una estructura de datos, queremos un entregable

Independientemente del concepto que tengas tú en mente, las repetidas correcciones que se te han hecho deberían darte una pista de que debes actualizar ese concepto. Por favor, hazlo.

2022-10-25 10:25 UTC, JJ commented on docs/Objetivo-1/milestones.md
> +- [M1] Diseño de una serie de ficheros que implemente la lógica de negocio y que use el Algoritmo de similitud de Pearson para encontrar libros lo más similar posible al libro proporcionado, según el
Los ficheros no se "diseñan". Por favor, escribid con precisión para describir la solución que proponéis a un problema de ingeniería.

2022-10-25 10:25 UTC, JJ commented on docs/Objetivo-1/milestones.md
> +- [M2] Implementación de una API que nos permita obtener datos del libro más similar al libro proporcionado.
¿Qué tipo de API? ¿Que resuelva qué historia de usuario? ¿Cómo tiene que estar esa implementación?

2022-10-25 10:25 UTC, JJ commented on docs/Objetivo-1/usuarios.md
> +Estudiante que busca leer para comentarlos con otras personas. Si puede ser, que sean novelas clásicas.
¿4 usuarios para una sola historia de usuario?

2022-10-25 15:51 UTC, fjgallardo00 commented on docs/Objetivo-1/historias_usuarios.md
> +- [HU1] Quiero que se me recomiende un libro que me guste, indicando otro segundo libro para que me encuentre un libro lo más similar posible.
Sobre el punto uno, no entiendo a qué se refiere con "Si sólo recomienda a quién ya sugiera un libro, no resuelve el problema original". Sobre el segundo punto, sé que mencionar otro libro sobre el que comparar excluye una lista de libros, puesto que el algoritmo compara la similitud de dos elementos concretos, no de una lista de valores. Para realizar una comparación con una lista de libros tendría que buscarme otro algoritmo, y por ende otra lógica de negocio.

2022-10-25 15:56 UTC, fjgallardo00 commented on docs/Objetivo-1/milestones.md
> +- [M0] Diseño de un módulo que defina la estructura de datos donde vayamos a almacenar libros y géneros.
No entiendo por qué no se trata de diseñar módulos si incluso en las transparencias sobre los PMV y los Milestones, el ejemplo del milestone 0 pone casi de forma literal "Diseño de un módulo para definir una estructura de datos". Si como dice no se trata de diseñar módulos, las transparencias tienen un fallo, y algún compañero que tiene aceptado el objetivo 1 no debería, pues también el milestone 0 lo tiene descrito como diseño de un módulo.

2022-10-25 16:00 UTC, fjgallardo00 commented on docs/Objetivo-1/usuarios.md
> +Estudiante que busca leer para comentarlos con otras personas. Si puede ser, que sean novelas clásicas.
Puesto que la historia de usuario que tengo es bastante impersonal o genérica, pensé en eliminar directamente estos usuarios.

2022-10-25 18:05 UTC, JJ reviewed
Sólo comentarios, porque no ha habido cambios.

2022-10-26 17:03 UTC, fjgallardo00 commented on docs/Objetivo-1/milestones.md
> +- [M0] Diseño de un módulo que defina la estructura de datos donde vayamos a almacenar libros y géneros.
No, evidentemente copiar y pegar no hace que yo entienda el concepto. Pero como usted me ha indicado varias veces, me lo explicó en clase, pero sigo aún sin entenderlo, así que eché mano del material de clase. Pero claro, me cuesta llegar a una conclusión clara si usted me dice que lo que yo he cogido del material está mal.

2022-10-26 17:09 UTC, fjgallardo00 commented on docs/Objetivo-1/milestones.md
> +- [M2] Implementación de una API que nos permita obtener datos del libro más similar al libro proporcionado.
Puesto que no sé como hacer que la descripción de la API sea mínima y viable, eliminaré ese milestone y si fuera necesario, lo añadiré más adelante.

2022-10-26 17:20 UTC, JJ commented on docs/Objetivo-1/milestones.md
> +- [M0] Diseño de un módulo que defina la estructura de datos donde vayamos a almacenar libros y géneros.
Pues por favor, trata de entender lo que te digo aquí y en clase, y en el marco del desarrollo ágil, que como sabes trata de resolver problemas.

2022-10-26 17:20 UTC, JJ commented on docs/Objetivo-1/milestones.md
> +- [M2] Implementación de una API que nos permita obtener datos del libro más similar al libro proporcionado.
Si no lo sabes no lo pongas. Sólo se exigen 2 milestones en este objetivo, ya habrá tiempo de escribir otros cuando llegue su momento.

2022-10-26 17:23 UTC, fjgallardo00 commented on docs/Objetivo-1/historias_usuarios.md
> +- [HU1] Quiero que se me recomiende un libro que me guste, indicando otro segundo libro para que me encuentre un libro lo más similar posible.
Pero el hacer que tengas una serie de libros leídos no hace que te recomiende una mejor opción, si en la lista de leídos por ejemplo hay una novela de ciencia ficción, otra novela es de terror y otro es un ensayo histórico, ¿cómo se sabe cuál sería la mejor recomendación? Cada libro no tiene nada que ver una cosa con la otra. Sin embargo, si se proporciona un libro con el que comparar para obtener una recomendación, sí que se pueden descartar como posibles recomendaciones aquellos libros que ya hayan sido leídos y que estén en una lista de leídos.

2022-10-26 17:28 UTC, JJ commented on docs/Objetivo-1/historias_usuarios.md
> +- [HU1] Quiero que se me recomiende un libro que me guste, indicando otro segundo libro para que me encuentre un libro lo más similar posible.
> Pero el hacer que tengas una serie de libros leídos no hace que te recomiende una mejor opción, si en la lista de leídos por ejemplo hay una novela de ciencia ficción, otra novela es de terror y otro es un ensayo histórico, ¿cómo se sabe cuál sería la mejor recomendación? Cada libro no tiene nada que ver una cosa con la otra. Sin embargo, si se proporciona un libro con el que comparar para obtener una recomendación, sí que se pueden descartar como posibles recomendaciones aquellos libros que ya hayan sido leídos y que estén en una lista de leídos.

¿No se supone que la lógica de negocio tiene que resolver eso? En todo caso, es lo que tú pusiste como descripción del problema.

En las historias de usuario tienes que describir diferentes posibilidades de uso: uno que no tenga ningún libro leído y que use la plataforma por primera vez, uno que tenga un montón de libros ya leídos en la plataforma donde un montón va de 1 a n, y cualquier otra historia de usuario que quieras poner (que sólo ponga géneros, yo qué sé, son *tus* historias de usuario)

2022-10-26 17:39 UTC, fjgallardo00 commented on docs/Objetivo-1/historias_usuarios.md
> +- [HU1] Quiero que se me recomiende un libro que me guste, indicando otro segundo libro para que me encuentre un libro lo más similar posible.
La lógica de negocio tiene que resolver que si te has quedado sin libros que leer, el sistema te recomiende un libro que no te hayas leído antes. La manera de hacer que te recomiende un libro se puede hacer de muchas maneras. La manera que yo creo que está mejor es la de indicar un libro para que te dé otro similar. Por ejemplo, si yo me he leído recientemente un ensayo sobre el Gran Capitán de los tercios españoles, quiero que el sistema me recomiende algo lo más parecido posible a un ensayo del Gran Capitán, o de los tercios españoles o algo similar que haya disponible. Esa es la manera que creo que debe ser la principal. Se pueden añadir otras maneras como las que me indica usted, como bien dice, tengo que indicarlo en las HU, porque lo que yo tengo está mal, pero la descripción del problema y la lógica de negocio creo que no tienen ningún tipo de incoherencia con lo que tengo en mente de lo que puede ser la aplicación.

2022-10-26 17:44 UTC, JJ commented on docs/Objetivo-1/historias_usuarios.md
> +- [HU1] Quiero que se me recomiende un libro que me guste, indicando otro segundo libro para que me encuentre un libro lo más similar posible.
Las historias de usuario no están para que tú decidas de antemano cuál es la mejor. Están para que los usuarios (que son los clientes) expresen sus intereses y qué problemas específicos tienen, en vista de cómo van a usar el sistema. Tú como desarrollador puedes priorizar una u otra, pero *no* puedes priorizar o "escoger" una que *no* resuelva el problema, porque hay que resolver problemas.
Te recuerdo que *tu* historia de usuario *no es* *toda* la historia de usuario. Convendría que entendiérais eso, porque la ingeniería de software es resolver problemas.

2022-10-27 09:13 UTC, fjgallardo00 commented
Listo para revisión.
@JJ @pedromarting3

2022-10-27 09:52 UTC, JJ approved these changes
👍

2022-10-27 09:52 UTC, JJ commented
Por favor, revisa alguno de los otros objetivos 1 que estén sin aprobar para poder asignártelo. Hazlo antes de la clase de mañana.

2022-10-27 10:33 UTC, pedromarting3 commented
Me alegro que hayas pasado el objetivo 1! @fjgallardo00 a por el siguiente 🚀

2022-10-27 10:36 UTC, merged